version: '3.9'
services:
  postgres:
    image: 'postgres:18.0'
    environment:
      POSTGRES_DB: 'wb_test'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    ports:
      - '7432:5432'
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -d wb_test -U admin']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
